### ISSUE TITLE
Radarr for dark mode cards

### ISSUE THREAD

**Issue by F1DNA** [NX211/homer-icons#18]
The current radarr icon doesn't bode well with a dark background
This one does:

https://avatars1.githubusercontent.com/u/25025331?s=200&v=4

**Comment by agneevX** [comment]
This icon looks different compared to the actual one.

**Comment by F1DNA** [comment]
> 
> 
> This icon looks different compared to the actual one.

Yes?  The "actual one" that is in this collection gets washed out when using a dark theme.  The one I linked shows up much better against a dark background.  See here for a comparison:

https://imgur.com/a/UAKzujN

![radarr_light](https://user-images.githubusercontent.com/61926834/121351829-cbfd9800-c8f1-11eb-8dcf-949f145e6c95.png)

Also, I see that we can simply add icons/logos as a pull request so I shall do that.

**Comment by agneevX** [comment]
I completely understand what you're going for, however it looks you've redrawn the logo because the glyphs look different. 


E.g. there's less padding inside, the black borders aren't consistent with what the actual icon is.

**Comment by F1DNA** [comment]
Oh, I didn't redraw.  I simply "borrowed" it from a duckduckgo image search.

https://duckduckgo.com/?q=radarr+logo&t=newext&atb=v242-1&iax=images&ia=images&iai=https%3A%2F%2Favatars1.githubusercontent.com%2Fu%2F25025331%3Fs%3D200%26v%3D4

**Comment by F1DNA** [comment]
As well, I have the logo/icon loaded into my homer container so I'm fine with what I have.  Just thought I would share what I found with others.  If there is some issue with this one and so it doesn't make the cut, that's fine.

**Comment by F1DNA** [comment]
I'm closing the "issue" based on, I'm not here to debate whether the black borders are consistent with what the actual icon is or not.  Sorry I submitted this, it's just an icon.  This one works better in my case, thought maybe it would for someone else as well.
