### ISSUE TITLE
New icon: deemix

### ISSUE THREAD

**Issue by KucharczykL** [NX211/homer-icons#22]
The icon can be found in their repo here: https://gitlab.com/RemixDev/deemix-webui/-/blob/main/public/favicon.ico

It's not the best quality, however.

**Comment by KucharczykL** [comment]
![favicon-0](https://user-images.githubusercontent.com/31072879/121497071-5a017d80-c9db-11eb-9803-38575c3333fb.png)

Converted to PNG.

**Comment by NX211** [comment]
I was able to find something a little higher quality and I've added it to the repo. Thanks for opening an issue

**Comment by KucharczykL** [comment]
Nice, that is a pretty good looking version. Thanks!
