### ISSUE TITLE
[Icon Request]

### ISSUE THREAD

**Issue by jakobstavenau** [NX211/homer-icons#29]
OpenWRT

**Comment by waschinski** [comment]
Opened a PR #30 for this.

**Comment by jakobstavenau** [comment]
> 
> 
> Opened a PR #30 for this.

Thank you, I'm new to this.

**Comment by waschinski** [comment]
> > Opened a PR #30 for this.
> 
> Thank you, I'm new to this.

You are welcome. @NX211 still needs to accept the PR though. Meanwhile you can grab the icon from my fork over at https://github.com/waschinski/homer-icons/blob/master/png/openwrt.png

**Comment by NX211** [comment]
Thank you both. I accepted the PR.
