### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [NX211/homer-icons#45]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

Creative Commons Attribution-ShareAlike be a good choice for the icons if you made them.

**Comment by fbartels** [comment]
There is also a fork circulating on Reddit (see https://www.reddit.com/r/selfhosted/comments/pmtd73/icons_for_your_personal_dashboard/hcnvsf3/?utm_source=reddit&utm_medium=web2x&context=3 where I already raised the question about the validity of the fork) which decided to add the "unlicense" license to this project.

The issue I see with this project is that unless all the icon files have been created yourself they may already have a license attached to it.

**Comment by WalkxCode** [comment]
> 
> 
> There is also a fork circulating on Reddit (see https://www.reddit.com/r/selfhosted/comments/pmtd73/icons_for_your_personal_dashboard/hcnvsf3/?utm_source=reddit&utm_medium=web2x&context=3 where I already raised the question about the validity of the fork) which decided to add the "unlicense" license to this project.
> 
> The issue I see with this project is that unless all the icon files have been created yourself they may already have a license attached to it.

This license has already been removed, and as you told me you cannot add a license to it as I don't own the icons. That also means this repository is not allowed to add a license.

**Comment by TechnologyClassroom** [comment]
The icons could be a different license from the code.  The code just generates the readme I believe, but that is generally one way that licensing could work.

**Comment by WalkxCode** [comment]
Alright!

**Comment by NX211** [comment]
Thanks for opening this issue @TechnologyClassroom.  I think @WalkxCode is right on this one. I can't  license anything that I did not create. This repo is just a collection of other peoples work. I think of this repo as a time saver at best and far from anything that I would consider a project.

**Comment by NX211** [comment]
Even the code just generates the readme was contributed by someone other than myself without the implicit understanding that their would be a license. The python script in question is also very basic and I don't know that it would benefit from licensing.

**Comment by TechnologyClassroom** [comment]
Makes sense.  You cannot license things you do not have the legal rights to license.
