### ISSUE TITLE
Add BlueIris Logo

### ISSUE THREAD

**Issue by Thormus** [NX211/homer-icons#46]
I am noob at github. Idk how to do a pull request but having the blue iris logo would be sweet.

**Comment by UntouchedWagons** [comment]
Here's the one I use, it's transparent too.

![blue-iris](https://user-images.githubusercontent.com/160996/147374506-6c34e73f-3d96-4fb0-bba5-8c53702a0bc4.png)

**Comment by NX211** [comment]
I've added the BlueIris logo that you provided. Thank you.
