### ISSUE TITLE
[🔗] Linking request to active fork

### ISSUE THREAD

**Issue by walkxcode** [NX211/homer-icons#58]
Hey @NX211,

I've noticed your homer-icons repo is kinda inactive lately, and I've made
a fork of ur repo with way more icons and native support of many
dashboards. I was wondering if since your repo is inactive, you could
archive it and put a link in the repo to my fork? Here's the link:
https://github.com/walkxcode/dashboard-icons

Greetings, Walkx.

**Comment by NX211** [comment]
You've got a great project going. When I posted the link to my repo on reddit I had no idea that it would be so popular. I use this repo for personal projects so it wouldn't work for me to archive it. I'm happy to direct everyone your way as it seems your project is a better fit for the general public.
