### ISSUE TITLE
[Enhancement] Addition of SoGo

### ISSUE THREAD

**Issue by modzilla99** [NX211/homer-icons#59]
Maybe you can add the following Icon:

![SoGo](https://hosted.mailcow.de/SOGo.woa/WebServerResources/img/sogo-full.svg)

**Comment by modzilla99** [comment]
and this one:

![Mailcow](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.h_DGM3Qy_-JjzbZY_NgeMAAAAA%26pid%3DApi&f=1)

**Comment by modzilla99** [comment]
And those as well:

![](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/oscam-logo.png)
![](https://upload.wikimedia.org/wikipedia/commons/8/8f/GNS3_logo.png)
![](https://dashboard.snapcraft.io/site_media/appmedia/2020/02/maas-logo-cropped.png)

**Comment by NX211** [comment]
the SoGo icon is in PR #50 Added Icons
