### ISSUE TITLE
Update portainer icon

### ISSUE THREAD

**Issue by Pheggas** [NX211/homer-icons#61]
I found an SVG so you can resize it to any resolution you want

[Here's the link](https://camo.githubusercontent.com/f243cb2f3d80109a529abba1f040fb67cb27bf0842506531db40567f9f22a1df/68747470733a2f2f63646e2e776f726c64766563746f726c6f676f2e636f6d2f6c6f676f732f706f727461696e65722e737667)

**Comment by walkxcode** [comment]
Heya! NX211 seems to be no longer working on this repo. I've added the icon to my fork of this repo. https://github.com/walkxhub/dashboard-icons

**Comment by NX211** [comment]
I've added both the svg and png to the repo. Thank you.
