### ISSUE TITLE
Add Soulseek icon

### ISSUE THREAD

**Issue by Pheggas** [NX211/homer-icons#62]
Could you add [Soulseek icon](https://en.wikipedia.org/wiki/Soulseek#/media/File:Soulseek-png-3.png)?

**Comment by walkxcode** [comment]
Heya! NX211 seems to be no longer working on this repo. I've added the icon to my fork of this repo. https://github.com/walkxhub/dashboard-icons

**Comment by NX211** [comment]
This repo is just a personal project to support my homelab. I try to accept PR's and respond to issues however, please feel free to fork the repo and tailor it to your needs.
