### ISSUE TITLE
Invoice Ninja icon is blank

### ISSUE THREAD

**Issue by UntouchedWagons** [NX211/homer-icons#66]
https://github.com/NX211/homer-icons/blob/master/png/invoiceninja.png

It's completely blank

**Comment by NX211** [comment]
Thank you for opening this issue. The Invoice Ninja icon is a white PNG image with a transparent background so it would appear blank on a white background. I will work on this and maybe add an outline.

**Comment by UntouchedWagons** [comment]
How about this one?

![invoiceninja](https://user-images.githubusercontent.com/160996/210183231-a4dc074b-7b89-4c43-af68-0ccb366560fc.png)
